### ISSUE TITLE
Changing people's models on skate/hoverboard

### ISSUE THREAD

**Issue by Killer-Bean** [civilgamers/bug-reports#21]
Summary of bug: Modelling players on skate/hoverboard to your skin 
Which server does this occur on?: CG
Steps to reproduce this bug: When someone is on a hoverboard or skateboard you can walk up to them and press E on them or the board and it turns them into your model but they stay as their own job.
Screenshot or recordings:  https://steamcommunity.com/id/Buckyyeoo/screenshot/790857769138610867

**Comment by anthonysharpy** [comment]
@Cerbiac Now that skateboards are gone should we close this?

**Comment by Cerbiac** [comment]
Nah. We'll keep it just in case.
