### ISSUE TITLE
Guns going through the floor

### ISSUE THREAD

**Issue by Lewis050303** [civilgamers/bug-reports#23]
Summary of bug:Entities and guns going through the floor and sitting in the gap between physical floor and skybox
Which server does this occur on?:CC
Steps to reproduce this bug:Last night I was spawning in routers while looking mostly at the ground and they were falling through the floor.
Screenshot or recordings:N/A

**Comment by HydroCG** [comment]
This is just a map thing, and it's really not easy to fix. The way the map is laid out it minimizes resources and sets a clear skybox-floor region. Without investing a significant amount of time into the map this isn't doable (and even after doing this there's no guarantee it will be fixed).

Consequently, there's better things for us to be spending dev time on.

Thanks for the report but this is going to be a wontfix.
