### ISSUE TITLE
Physgunning Skateboards Can Move Entities

### ISSUE THREAD

**Issue by Mathematical-Jin** [civilgamers/bug-reports#287]
**Hello Developers,**
I was in an admin sit and this guy mentioned a bug that he came across saying that people can push the skateboard using their physgun into players insta-killing them. He also mentioned that he can move entities with the skateboard such as cars and e.t.c. I tested this myself and he seems to be correct.

**Kind Regards**

**Jin**

**Comment by Tiin57** [comment]
no fuck off
