### ISSUE TITLE
VBusiness ATMs don't show data on first attempt

### ISSUE THREAD

**Issue by Erik-Glover** [civilgamers/bug-reports#34]
the thing is broken since ages, if you press e on one of the custom bank machines it has a black screen, you need to leave and reenter until it actually works

https://steamcommunity.com/sharedfiles/filedetails/?id=1655260264

**Comment by Cerbiac** [comment]
Bug since May. Yikes ;-;

**Comment by Cerbiac** [comment]
And with that noted, haven't heard the bug since. Presumably fixed.
