### ISSUE TITLE
Riding hoverboards/skateboards when wanted

### ISSUE THREAD

**Issue by Killer-Bean** [civilgamers/bug-reports#4]
So basically Ventz has mentioned in Discord change logs that riding a hoverboard and skateboard while wanted was not going to be possible anymore starting by today's restart even though you still can. I have a screenshot with Gyazo of this happening to me. Quality is not good for some reason but here it is anyway - https://gyazo.com/55a7b91992a95ffb1ce85d3a04e99fe3

**Comment by Killer-Bean** [comment]
was fixed

**Comment by Tiin57** [comment]
was fixed
