### ISSUE TITLE
Lua error "ventz_trust_funds"

### ISSUE THREAD

**Issue by Cherry2002** [civilgamers/bug-reports#425]
Hello i don't know why this happend but i just wanted to report it.
"
[ERROR] lua/includes/extensions/math.lua:154: attempt to perform arithmetic on local 'num' (a nil value)
  1. Round - lua/includes/extensions/math.lua:154
   2. unknown - addons/ventz_trust_funds/lua/entities/trust_fund_viewer/cl_init.lua:38

"

![image](https://user-images.githubusercontent.com/53127270/63218373-03191d00-c151-11e9-9cab-25c2c8bea66e.png)

**Comment by Tiin57** [comment]
fixed on restart
