### ISSUE TITLE
NPC Tags Hidden

### ISSUE THREAD

**Issue by Cherry2002** [civilgamers/bug-reports#516]
This is not a game breaking bug but i think its working letting the devs know if they update  the map or something. Anyway the water effect is hiding the name tags for the npc's  

[screenshot one](https://i.imgur.com/wmqnanR.jpg)
[screenshot two](https://i.imgur.com/7ri7zUL.jpg)
[screenshot three](https://i.imgur.com/UNyraCt.jpg)

**Comment by Cerbiac** [comment]
Fixed
