### ISSUE TITLE
Opening F4 as Black Market Dealer causes lag

### ISSUE THREAD

**Issue by Erik-Glover** [civilgamers/bug-reports#53]
Reported by jwcsg https://giant.gfycat.com/GoldenSecondhandHawk.webm

**Comment by dhog10** [comment]
Run FProfiler, start, open F4, end profile, screenshot result and post here please

**Comment by HydroCG** [comment]
[img]https://i.imgur.com/cflISkc.jpg[/img]

**Comment by anthonysharpy** [comment]
Probably fixed. Was caused by the menu initialising a new Material() every :Paint() function. Cached the result instead in multiple places.

**Comment by HydroCG** [comment]
Not fixed, or atleast not applied to cg. This needs fixing. Is also broken on tree man and other jobs

**Comment by HydroCG** [comment]
https://github.com/civilgamers/amethyst_f4/pull/4

**Comment by anthonysharpy** [comment]
I fixed this and gave the files to Ventz but he did not implement.
