### ISSUE TITLE
BluesATM: People are being hidden behind it

### ISSUE THREAD

**Issue by Cherry2002** [civilgamers/bug-reports#548]
Evidence: 
-  https://i.imgur.com/s69ETTa.jpg
-  https://i.imgur.com/GKUCgQJ.jpg

**Comment by Cerbiac** [comment]
Depends on the player model. Seen this happen before.

**Comment by Cherry2002** [comment]
Still a bug. If its not going to be fixed, close it.

**Comment by HydroCG** [comment]
The rendering technique the cash machines use means that it needs to turn off z-depth comparisons. This means that it can't tell what is infront of it, or what's behind it. Fundamentally, this is just a drawback of having the cash machines drawn in walls. (You can also get this behaviour with other addons that do similar things)
