### ISSUE TITLE
Switching jobs with conglomerate armor removes speed debuff

### ISSUE THREAD

**Issue by Erik-Glover** [civilgamers/bug-reports#57]
the bug is fixed on cc.

if you buy congo armor, equip it , switch job and you run at all full speed again.
This thing is already fixed on cc , but was never ported to the main one.

**Comment by Cerbiac** [comment]
Happens when unarrested too.

**Comment by Cerbiac** [comment]
Bump

**Comment by HydroCG** [comment]
Should be deployed to CG after reboot.
