### ISSUE TITLE
Mining factories bug

### ISSUE THREAD

**Issue by Mystic-Ace** [civilgamers/bug-reports#6]
Two of the Mining Factories are in locations that currently force the carts into locations that they then become unobtainable and have to be removed by an SA+ 
![dbdfa559e0551b8ade2e69268572cc3f-jpg](https://user-images.githubusercontent.com/51122589/58479759-c2f95e00-8150-11e9-8d33-b04a9e57e611.jpg)
![a5d77418707c9a5a7a5aeedbeafa958c-jpg](https://user-images.githubusercontent.com/51122589/58479770-c68ce500-8150-11e9-80fc-269b20b16c65.jpg)

Image 1: Show's the factory at the bottom of the cave near the lagoon type area. 
Image 2: Show's the factory at the bottom of the cave at the climbing mining shaft.

**Comment by HydroCG** [comment]
They have been removed.
