### ISSUE TITLE
Non-VIP can use Elite Cong printer

### ISSUE THREAD

**Issue by Killer-Bean** [civilgamers/bug-reports#7]
So when I check the donation store on the website it says that when you buy certain VIP ranks you get access to the elite cong printer as long as you're in a conglomerate org. I have a screenshot of someone who was in a conglomerate org but had no sort of VIP at all. Here is a screenshot --  https://steamcommunity.com/id/Buckyyeoo/screenshot/781851130168334130

**Comment by Tiin57** [comment]
Should be fixed after restart.

**Comment by dhog10** [comment]
Fixed?
