### ISSUE TITLE
Bad item index bug

### ISSUE THREAD

**Issue by Shrimpzs** [civilgamers/bug-reports#712]
### Description 
This bug happens when you move guns or items around your inventory Idk if this only happens to me, it can get make guns disappear from your inventory making me lose a few guns including a GOL magnum. that cost me a lot.

### Steps to Reproduce 

1. get an item from your inventory
2. click and click on another space
3. boom bad item index

**Expected Behavior** 
The gun moves to the other space

**Actual Behavior** 
it says bad item index and disappears then I need to click on the space where it's gone and it reappears (most of the time this works)

### Evidence

 
![image](https://user-images.githubusercontent.com/61356405/75095299-55545400-5561-11ea-80a1-35e56df4ce6d.png)

![image](https://user-images.githubusercontent.com/61356405/75095308-70bf5f00-5561-11ea-8cfb-a3048e9269e8.png)
gun right there but gone

**Comment by HydroCG** [comment]
fixed
