### ISSUE TITLE
CC | D.C.O is arrestable 

### ISSUE THREAD

**Issue by ghost** [civilgamers/bug-reports#722]
### Description 

The new job 'D.C.O' is able to be arrested by members of the PD in which 'D.C.O' is part of the PD.

### Steps to Reproduce 

1.  Become 'D.C.O' thought the F4 menu
2.  Ask a member of the PD with a taser and arrest baton to tase you and arrest you

**Expected Behavior** 

When 'D.C.O' gets hit with a taser it should do no effect at all.

**Actual Behavior** 

When 'D.C.O' gets hit with a taser they drop to the ground in which they can be arrested when hit with an arrest baton

**Comment by cloakical** [comment]
patched in cc 3.0 build
