### ISSUE TITLE
Unarresting through maxnet

### ISSUE THREAD

**Issue by InsaneEruptt** [civilgamers/bug-reports#731]
### Description 

When you try unarrest someone through maxnet it ends the remote connection and doesn't unarrest the person.

### Steps to Reproduce 

1.  Hack into PD
2. Try unarrest someone
3. 

**Expected Behavior** 

Should unarrest the person who you try to unarrest

**Actual Behavior** 

Ends the remote connection with PD and makes you reconnect

### Evidence
https://prnt.sc/sa64v9

**Comment by quantix-dev** [comment]
You hacked in wrong.

I don't think I can say much about how to do it properly though

**Comment by relz999** [comment]
You are not hacking the PD correctly. This is expected behaviour.
