### ISSUE TITLE
I got banned for no reason i did

### ISSUE THREAD

**Issue by siggen1234** [civilgamers/bug-reports#732]
### Description 

 I got banned for no reason

### Steps to Reproduce 

1. Unban me
2. find the guy that did it
3. 

**Expected Behavior** 

 Nothing, i was trying to join

**Actual Behavior** 

 i was joining and then i got banned

### Evidence

  
![image](https://user-images.githubusercontent.com/64858398/81093133-f0728e00-8f01-11ea-8032-d43cfd50d6c7.png)
![Skjermbilde](https://user-images.githubusercontent.com/64858398/81093205-0a13d580-8f02-11ea-8399-084506db6bf0.PNG)

**Comment by ghost** [comment]
Please don't post ban appeals here again.
