### ISSUE TITLE
(CC) Virus scanner not letting anyone through it

### ISSUE THREAD

**Issue by Douglas2122002** [civilgamers/bug-reports#734]
### Description 
Scanners that are spawned in part of the map, and even the ones spawned in from the F4 menu is bugged and no one or car can go through it, almost like it's a  #prop

### Method 1
1. Try to walk through the map spawned one
### Method 2
1. Spawn in virus scanner and deploy it
2. Walk through it (it won't let you) 
**Expected Behavior** 
To be able to walk through it like it used to do

**Actual Behavior** 
It won't let any player or even a car for that matter pass through

**Comment by Rovester** [comment]
This should be fixed now, ventz changed it yesterday really late.
