### ISSUE TITLE
CC | Criminal Skilltree perk 'Lockpick Proficiency' often not applied.

### ISSUE THREAD

**Issue by NotTeeZee** [civilgamers/bug-reports#736]
### Description 

When you have the 'lockpick proficiency' perk unlocked in the criminal skilltree, it gives you -5s lockpick time. However, this usually doesnt work (like 80% of the time?).

### Steps to Reproduce 

1. Get the perk 'lockpick proficiency' (preferably to lvl 5 for highest contrast)
2. Get a lockpick, use it on a door/fading door
3. Try lockpicking a few times
4. Observe
5. Come to the conclusion that more often than not, the skilltree perk is not applied.

**Expected Behavior** 

For the skilltree perk to be applied everytime, so you know how much time you'll need to lockpick something (it's more RNG bound now, which can result in nasty RP-situations).

**Actual Behavior** 

The skilltree perk is often not applied during lockpicking.

### Evidence

Skilltree perk: https://i.imgur.com/DIVIUxp.png
Behaviour: https://gfycat.com/InferiorWarpedHagfish

**Comment by relz999** [comment]
@NotTeeZee when an entity such as a car, door, etc. is lockpicked it will first check if there is a specified time assigned. If an assigned lockpick time does not exist, it will randomly generate a value between 10 and 30 seconds to use. The skill will then deduct from this e.g. between 5 to 25 seconds.
