### ISSUE TITLE
PD radio: /chandown while someone's talking makes constant static

### ISSUE THREAD

**Issue by Erik-Glover** [civilgamers/bug-reports#74]
this is still a problem and has not been fixed, if are PD and someone talks while you do /chandown you will keep hearing the radio static until you go back to the channel that person was speaking in and talks once again. when that person is done speaking its fixed. and otherwise, you're stuck with this really annoying static sounds that doesn't go away, or you have to switch job.

**Comment by HydroCG** [comment]
Unable to repro on CivilCity
