### ISSUE TITLE
[CC] Mechanic tow truck issue 

### ISSUE THREAD

**Issue by DrabberG** [civilgamers/bug-reports#82]
Basically , when a mechanic decides to retrieve their tow truck it does not spawn next to the tow truck dealer ( NPC ) . It instead spawns half way in the ground outside industrial which could cause the server to crash if prop pushed. ( I think ) 

https://steamcommunity.com/sharedfiles/filedetails/?id=1757375043

**Comment by dhog10** [comment]
Fixed
